todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TaskCreateView,
    task_done_not_done,
    TagsListView,
    TagCreateView
)


urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("task-create/", TaskCreateView.as_view(), name="task-create"),
    path("task-complete/<int:pk>/", task_done_not_done, name="task-complete"),
    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tag-create/", TagCreateView.as_view(), name="tag-create"),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(null=True, blank=True)
    is_completed = models.BooleanField()
    tags = models.ManyToManyField("Tag", related_name="tasks", blank=True)

    class Meta:
        ordering = ("is_completed", "datetime")


class Tag(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self) -> str:
        return self.name

todo/forms.py
from django import forms

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

todo/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from todo.forms import TaskForm
from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


def task_done_not_done(request: HttpRequest, pk: int) -> HttpResponse:
    task = Task.objects.get(id=pk)

    task.is_completed = not task.is_completed

    task.save()

    return HttpResponseRedirect(reverse("todo:task-list"))


class TagsListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tags-list")

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

  {% block title %}<title>Todo List</title>{% endblock %}

</head>

<body>
  <div class="container-fluid">
    <div class="row">

      <div class="col-sm-2">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>

      <div class="col-sm-10">
        {% block content %}{% endblock %}
      </div>

    </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<br>
<ul class="list-group">
  <li class="list-group-item">
    <a href="{% url "todo:task-list" %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url "todo:tags-list" %}">Tags</a>
  </li>
</ul>

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary submit-button">
  </form>
  <a href="{% url "todo:tags-list" %}" class="btn btn-dark mt-3">Cancel</a>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <br>
  <h1>
    Tags
    <a href="{% url "todo:tag-create" %}" class="btn btn-primary" style="float: right">Add</a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for tag in tag_list %}
          <tr>
            <td>{{ tag.name }}</td>
            <td><a href="#" class="btn btn-secondary">Update</a></td>
            <td>
              <a href="#" class="btn btn-secondary">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no tags yet.</p>
  {% endif %}
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary submit-button">
  </form>
  <a href="{% url "todo:task-list" %}" class="btn btn-dark mt-3">Cancel</a>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <br>
  <h1>Todo list
  <a href="{% url "todo:task-create" %}" class="btn btn-primary" style="float: right">Add Task</a>
  </h1>
  <br>

  {% if task_list %}
      {% for task in task_list %}
        {% if not task.is_completed %}
          <p>
            <strong>{{ task.content }}</strong> <strong style="color: red">Not done</strong>
            <a href="{% url "todo:task-complete" task.id %}" class="btn btn-success" style="float: right">Complete</a>
          </p>
        {% else %}
          <p>
            <strong>{{ task.content }}</strong> <strong style="color: green">Done</strong>
            <a href="{% url "todo:task-complete" task.id %}" class="btn btn-secondary" style="float: right">Undo</a>
          </p>
        {% endif %}
        <p>
          Created: {{ task.datetime }}
          {% if task.deadline %}
            <span style="color: darkred">Deadline: {{ task.deadline }}</span>
          {% endif %}
        </p>
        {% if task.tags.all %}
          <p>
            Tags:
            {% for tag in task.tags.all %}
              {{ tag.name }}
            {% endfor %}
          </p>
        {% else %}
          <p>There are no tags yet.</p>
        {% endif %}
        <a href="#">Update</a> <a href="#">Delete</a>
        <hr>
      {% endfor %}
  {% else %}
    <span>There are no tasks yet.</span>
  {% endif %}
{% endblock %}